version: '3'
services:
  database:
    image: 'postgres'
    container_name: 'postgresdb'
    environment: 
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=kioskdb
    ports:
      - '127.0.0.1:5432:5432'