export const USER_LOADING_ACTION = 'USER_LOADING_ACTION';
export const USER_LOADED_ACTION = 'USER_LOADED_ACTION';
export const USER_NOT_AUTHED = 'USER_NOT_AUTHED';
export const USER_UPDATING_ACTION = 'USER_UPDATING_ACTION';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';
export const USER_VERIFIED = 'USER_VERIFIED';

export const SCHEDULE_LOADING = 'SCHEDULE_LOADING';
export const SCHEDULE_LOADED = 'SCHEDULE_LOADED';
export const SCHEDULE_EMPTY = 'SCHEDULE_EMPTY';
export const SCHEDULE_SLOT_LOADING = 'SCHEDULE_SLOT_LOADING';
export const SCHEDULE_SLOT_FAILED = 'SCHEDULE_SLOT_FAILED';
export const SCHEDULE_SET_SLOT = 'SCHEDULE_SET_SLOT';
export const SCHEDULE_REQUESTING_SLOT = 'SCHEDULE_REQUESTING_SLOT';
export const SCHEDULE_SLOT_REQUEST_FAILED = 'SCHEDULE_SLOT_REQUEST_FAILED';
export const SCHEDULE_CANCEL_SLOT = 'SCHEDULE_CANCEL_SLOT';
