export const USER_LOADING_ACTION = 'USER_LOADING_ACTION';
export const USER_LOADED_ACTION = 'USER_LOADED_ACTION';
export const USER_NOT_AUTHED = 'USER_NOT_AUTHED';

export const SCHEDULE_LOADING = 'SCHEDULE_LOADING';
export const SCHEDULE_LOADED = 'SCHEDULE_LOADED';
export const SCHEDULE_EMPTY = 'SCHEDULE_EMPTY';
